# Generated by Django 3.2.5 on 2022-06-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Python2104',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=50)),
                ('tuoi', models.IntegerField()),
                ('diachi', models.TextField()),
            ],
            options={
                'db_table': 'Python2104',
            },
        ),
    ]
