# Generated by Django 3.2.5 on 2022-07-14 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0005_auto_20220702_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvarta',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('avarta', models.ImageField(upload_to='avarta')),
            ],
        ),
    ]
