# Generated by Django 3.2.5 on 2022-07-14 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_useravarta'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useravarta',
            table='UserAvarta',
        ),
    ]
